AppBundle\Entity\AddressBook:
    type: entity
    repositoryClass: AppBundle\Repository\AddressBookRepository
    table: address_book
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: f_name
        lName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: l_name
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        zCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: z_code
        city:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        country:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        number:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        birthdate:
            type: date
            nullable: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        pic:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        creationDate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: creation_date
        published:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '-1'
    lifecycleCallbacks: {  }
